#!/bin/bash

## Set login wallpaper

# strip new line char passed by Nautilus
FILENAME=$(echo $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS | sed -e 's/\r//g')

# Multiple files can't be selected.
LINE_COUNT=$(wc -l <<< "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS")
LINE_COUNT=$((LINE_COUNT-1))

if [[ $LINE_COUNT > 1 ]] ; then
    notify-send --urgency=normal "Failed to set wallpaper" "Ony one file can be selected at a time! "
    exit 1
fi

# Object type must be "file..." (ie no directories, etc.)
if [ -d "${FILENAME}" ] ; then
    notify-send --urgency=normal "Failed to set wallpaper" "${FILENAME} is a directory!";
    exit 1
else
    if [ -f "${FILENAME}" ]; then
        : # Bash noop
    else
        notify-send --urgency=normal "Failed to set wallpaper" "${FILENAME} is not a file!";
        exit 2
    fi
fi

if [ ${FILENAME: -4} != ".png" ] && [ ${FILENAME: -4} != ".jpg" ] && \
   [ ${FILENAME: -4} != ".bmp" ] && [ ${FILENAME: -4} != ".jpeg" ] && \
   [ ${FILENAME: -4} != ".tiff" ] && [ ${FILENAME: -4} != ".tif" ]; then
    notify-send --urgency=normal "Failed to set wallpaper" "${FILENAME} is not an image";
    exit 2
fi

gsettings set org.gnome.desktop.background picture-uri file://$FILENAME
gsettings set org.gnome.desktop.screensaver picture-uri file://$FILENAME

# Build working file in /tmp
#echo "[com.canonical.unity-greeter]" > /tmp/set-login-wallpaper.tmp
#echo "draw-user-backgrounds=false" >> /tmp/set-login-wallpaper.tmp
#echo "background='$FILENAME'" >> /tmp/set-login-wallpaper.tmp

# Must run as sudo
#if [ "$EUID" -ne 0 ] ; then

    # Get sudo password
#    PASSWORD=$(zenity --password --title="Set Login Wallpaper" --timeout=20)

    # copy working file to real file using sudo
#    echo $PASSWORD | sudo -S cp /tmp/set-login-wallpaper.tmp \
# /usr/share/glib-2.0/schemas/10_unity_greeter_background.gschema.override

    # compile using sudo
#    echo $PASSWORD | sudo -S glib-compile-schemas /usr/share/glib-2.0/schemas

#else
    # Already sudo so simply copy and compile
    # copy working file to real file
#    cp /tmp/set-login-wallpaper.tmp \
#/usr/share/glib-2.0/schemas/10_unity_greeter_background.gschema.override

    # compile
#    glib-compile-schemas /usr/share/glib-2.0/schemas
#fi

exit 0
